/*
    Copyright (c) 2012 Preet Desai (preet.desai@gmail.com)

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files (the
    "Software"), to deal in the Software without restriction, including
    without limitation the rights to use, copy, modify, merge, publish,
    distribute, sublicense, and/or sell copies of the Software, and to
    permit persons to whom the Software is furnished to do so, subject to
    the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
    LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
    OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
    WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

const char * globals_js =
"\n"
"// ================================================================ //\n"
"// WARNING: Don't edit this file unless you know what're doing! \n"
"// ================================================================ //\n"
"\n"
"function LiteralDataObj()\n"
"{\n"
"    this.value = false;\n"
"    this.valueIfFalse = \"\";\n"
"    this.valueIfTrue = \"\";\n"
"    this.property = \"\";\n"
"}\n"
"\n"
"function NumericalDataObj()\n"
"{\n"
"    this.value = 0;\n"
"    this.min = 0;\n"
"    this.max = 0;\n"
"    this.units = \"\";\n"
"    this.property = \"\";\n"
"}\n"
"\n"
"function ListDataObj()\n"
"{\n"
"    this.listData = [];\n"
"\n"
"    this.appendData = function(newData)\n"
"         {   this.listData.push(newData);   }\n"
"\n"
"    this.clearData = function()\n"
"         {   this.listData.length = 0;   }\n"
"}\n"
"\n"
"var global_list_num_data = new ListDataObj();\n"
"\n"
"var global_list_lit_data = new ListDataObj();\n"
"\n"
"function saveNumericalData(numDataObj)\n"
"{   global_list_num_data.appendData(numDataObj);   }\n"
"\n"
"function saveLiteralData(litDataObj)\n"
"{   global_list_lit_data.appendData(litDataObj);   }\n"
"\n"
"function DataBytesObj()\n"
"{\n"
"    this.bytes = [];\n"
"\n"
"    this.BYTE = function(bytePos)\n"
"         { return ((bytePos > -1 && bytePos < this.bytes.length) ? this.bytes[bytePos] : 0); }\n"
"\n"
"    this.BIT = function(bytePos,bitPos)\n"
"         {\n"
"             if(bytePos > -1 && bytePos < this.bytes.length && bitPos > -1 && bitPos < 8)\n"
"             {\n"
"                 var byteVal = this.bytes[bytePos];\n"
"                 if((byteVal & (1 << bitPos)) > 0)\n"
"                 {   return 1;   }\n"
"                 else\n"
"                 {   return 0;   }\n"
"             }\n"
"         }\n"
"         \n"
"    this.LENGTH = function()\n"
"         {   return this.bytes.length;   }\n"
"\n"
"    this.appendByte = function(byteVal)\n"
"         {\n"
"             if(byteVal >= 0)\n"
"             {   this.bytes.push(byteVal);   }\n"
"         }\n"
"\n"
"    this.clearData = function()\n"
"         {   this.bytes.length = 0;   }\n"
"}\n"
"\n"
"function ListDataBytesObj()\n"
"{\n"
"   this.listDataBytes = [];\n"
"   \n"
"   this.appendDataBytes = function(dataBytes)\n"
"      {\n"
"         var dataBytesObj = new DataBytesObj();\n"
"         dataBytesObj.bytes = dataBytes;\n"
"         this.listDataBytes.push(dataBytesObj);\n"
"      }\n"
"      \n"
"   this.clearDataBytes = function()\n"
"      {   this.listDataBytes.length = 0;   }\n"
"}\n"
"\n"
"// global list of databytes for when a given parameter\n"
"// needs to be reconstructed from multiple messages\n"
"var global_list_databytes = new ListDataBytesObj();\n"
"\n"
"function DATA(respNum)\n"
"{\n"
"   if(respNum > -1 && respNum < global_list_databytes.listDataBytes.length)\n"
"   {   return global_list_databytes.listDataBytes[respNum];   }\n"
"   else\n"
"   {   return 0;   }\n"
"}\n"
"\n"
"function BYTE(bytePos)\n"
"{   return DATA(0).BYTE(bytePos);   }\n"
"\n"
"function BIT(bytePos,bitPos)\n"
"{   return DATA(0).BIT(bytePos,bitPos);   }\n"
"\n"
"function LENGTH()\n"
"{   return DATA(0).LENGTH();   }\n"
"";
